CREATE TABLE "GUESTBOOK" (
  "IDX" NUMBER(5,0) NOT NULL, 
	"NAME" CHAR(20 BYTE) NOT NULL, 
	"PASSWORD" CHAR(20 BYTE) NOT NULL, 
	"CONTENT" VARCHAR2(500 BYTE) NOT NULL, 
	"WRITEDATE" TIMESTAMP (6) DEFAULT sysdate, 
	"IP" CHAR(15 BYTE), 
	PRIMARY KEY ("IDX")
);

DELETE FROM guestbook;
DROP SEQUENCE guestbook_idx_seq;
CREATE SEQUENCE guestbook_idx_seq;

SELECT * FROM guestbook ORDER BY idx DESC;